############################################################### -*- Makefile -*-
#
# Filename:  Makefile
#
# Summary:   
# 
# Notes:
#   This file is only for use with GNU make version 3.78.1 or greater
#
################################################################################

C++ = g++

LIB_SUFFIX = so

C++FLAGS = -g -O3 -fpic

LD = ${C++}
LD_FLAGS = -fpic -shared

include fedTime.mk


