############################################################### -*- Makefile -*-
#
# Filename:  Makefile
#
# Author(s): J. Olszewski
#
# Summary:   This file is only for use with GNU make version 3.78.1 or greater
#
# History:
#   Sep 1999  J. Olszewski    initial release.
#
#                      SAIC/OSC/VTC (All Rights Reserved)
################################################################################

default wicked-spotless clean:
	$(MAKE) -C src $(MFLAGS) $(MAKECMDGOALS)

