
/*******************************************************************************
       endTestModeDialog.h
       This header file is included by endTestModeDialog.cc

*******************************************************************************/

#ifndef _ENDTESTMODEDIALOG_INCLUDED
#define _ENDTESTMODEDIALOG_INCLUDED

#include <stdio.h>

#ifdef MOTIF
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/DialogS.h>
#include <Xm/MenuShell.h>
#endif /* MOTIF */

#include "UxXt.h"

#ifndef XKLOADDS
#define XKLOADDS
#endif /* XKLOADDS */

/*******************************************************************************
       The definition of the interface class.
       If you create multiple copies of your interface, the class
       ensures that your callbacks use the variables for the
       correct copy.

       For each swidget in the interface, each argument to the Interface
       function, and each variable in the Interface Specific section of the
       Declarations Editor, there is an entry in the class protected section.
       Additionally, methods generated by the builder are declared as 
       virtual. Wrapper functions are generated for callbacks and actions
       to call the user defined callbacks or actions. A UxDestroyContextCB()
       is also generated to ensure a proper clean up of the class after
       the toplevel is destroyed.
*******************************************************************************/

class _UxCendTestModeDialog: public _UxCInterface
{

// Generated Class Members

public:

 // Constructor Function
 _UxCendTestModeDialog( swidget UxParent );

 // Destructor Function
 ~_UxCendTestModeDialog();

 // Interface Function
 Widget _create_endTestModeDialog( void );

protected:

 // Widgets in the interface
 Widget endTestModeDialog;

 // Arg List of creation function
 swidget UxParent;

 // Callbacks and their wrappers

 // Callback function to destroy the context
 static void  UxDestroyContextCB(Widget, XtPointer, XtPointer);

private:
 Widget _build();
 CPLUS_ADAPT_CONTEXT(_UxCendTestModeDialog)

// User Supplied Class Members

} ;


/*******************************************************************************
       Declarations of global functions.
*******************************************************************************/

Widget create_endTestModeDialog( swidget UxParent );

#endif /* _ENDTESTMODEDIALOG_INCLUDED */
