
/*******************************************************************************
       genericPromptDialog.h
       This header file is included by genericPromptDialog.cc

*******************************************************************************/

#ifndef _GENERICPROMPTDIALOG_INCLUDED
#define _GENERICPROMPTDIALOG_INCLUDED

#include <stdio.h>

#ifdef MOTIF
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/MenuShell.h>
#endif /* MOTIF */

#include "UxXt.h"

#ifndef XKLOADDS
#define XKLOADDS
#endif /* XKLOADDS */

/*******************************************************************************
       The definition of the interface class.
       If you create multiple copies of your interface, the class
       ensures that your callbacks use the variables for the
       correct copy.

       For each swidget in the interface, each argument to the Interface
       function, and each variable in the Interface Specific section of the
       Declarations Editor, there is an entry in the class protected section.
       Additionally, methods generated by the builder are declared as 
       virtual. Wrapper functions are generated for callbacks and actions
       to call the user defined callbacks or actions. A UxDestroyContextCB()
       is also generated to ensure a proper clean up of the class after
       the toplevel is destroyed.
*******************************************************************************/

class _UxCgenericPromptDialog: public _UxCInterface
{

// Generated Class Members

public:

 // Constructor Function
 _UxCgenericPromptDialog( swidget UxParent, ServiceID serviceID );

 // Destructor Function
 ~_UxCgenericPromptDialog();

 // Interface Function
 Widget _create_genericPromptDialog( void );

protected:

 // Widgets in the interface
 Widget genericPromptDialog;
 Widget genericPromptForm;
 Widget instructionsLabel;
 Widget separator1;
 Widget extendedModeBtn;
 Widget variableForm;
 Widget placeHolder;
 Widget promptLabel;
 Widget promptTextField;
 Widget separator2;
 Widget orderTypeLabel;
 Widget orderTypeMenu;
 Widget receiveItem;
 Widget timestampItem;
 Widget menu3;
 Widget transportTypeLabel;
 Widget transportationTypeMenu;
 Widget reliableItem;
 Widget bestEffortItem;
 Widget menu4;
 Widget separator3;
 Widget promptDialogOkBtn;
 Widget promptDialogCancelBtn;
 Widget promptDialogHelpBtn;
 Widget placeHolder2;

 // Arg List of creation function
 swidget UxParent;
 ServiceID serviceID;

 // Callbacks and their wrappers
 virtual void  valueChangedCB_extendedModeBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_valueChangedCB_extendedModeBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_promptDialogOkBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_promptDialogOkBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_promptDialogCancelBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_promptDialogCancelBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_promptDialogHelpBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_promptDialogHelpBtn(Widget, XtPointer, XtPointer);
 // Callback function to destroy the context
  static void  UxDestroyContextCB(Widget, XtPointer, XtPointer);

private:
 Widget _build();
 CPLUS_ADAPT_CONTEXT(_UxCgenericPromptDialog)

// User Supplied Class Members
 virtual void  buildVariableForm (DialogStates, ModeStates);
} ;


/*******************************************************************************
       Declarations of global functions.
*******************************************************************************/

Widget create_genericPromptDialog( swidget UxParent, ServiceID serviceID );

#endif /* _GENERICPROMPTDIALOG_INCLUDED */

