
/*******************************************************************************
       helpSelectionShell.h
       This header file is included by helpSelectionShell.cc

*******************************************************************************/

#ifndef _HELPSELECTIONSHELL_INCLUDED
#define _HELPSELECTIONSHELL_INCLUDED

#include <stdio.h>

#ifdef MOTIF
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/MenuShell.h>
#endif /* MOTIF */

#include "UxXt.h"

#ifndef XKLOADDS
#define XKLOADDS
#endif /* XKLOADDS */

/*******************************************************************************
       The definition of the interface class.
       If you create multiple copies of your interface, the class
       ensures that your callbacks use the variables for the
       correct copy.

       For each swidget in the interface, each argument to the Interface
       function, and each variable in the Interface Specific section of the
       Declarations Editor, there is an entry in the class protected section.
       Additionally, methods generated by the builder are declared as 
       virtual. Wrapper functions are generated for callbacks and actions
       to call the user defined callbacks or actions. A UxDestroyContextCB()
       is also generated to ensure a proper clean up of the class after
       the toplevel is destroyed.
*******************************************************************************/

class _UxChelpSelectionShell: public _UxCInterface
{

// Generated Class Members

public:

 // Constructor Function
 _UxChelpSelectionShell( swidget UxParent, ServiceID serviceID );

 // Destructor Function
 ~_UxChelpSelectionShell();

 // Interface Function
 Widget _create_helpSelectionShell( void );

protected:

 // Widgets in the interface
 Widget helpSelectionShell;
 Widget bulletinBoard;
 Widget helpOptionsBoxLabel;
 Widget helpTypesMenu;
 Widget specHelpItem;
 Widget APIhelpItem;
 Widget bothHelpItem;
 Widget menu1;
 Widget separator;
 Widget helpSelectionCancelBtn;

 // Arg List of creation function
 swidget UxParent;
 ServiceID serviceID;

 // Callbacks and their wrappers
 virtual void  popupCB_helpSelectionShell(Widget, XtPointer, XtPointer);
 static void  Wrap_popupCB_helpSelectionShell(Widget, XtPointer, XtPointer);
 virtual void  activateCB_helpSelectionOkBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_helpSelectionOkBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_helpSelectionCancelBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_helpSelectionCancelBtn(Widget, XtPointer, XtPointer);

 // Callback function to destroy the context
 static void  UxDestroyContextCB(Widget, XtPointer, XtPointer);

private:
 Widget _build();
 CPLUS_ADAPT_CONTEXT(_UxChelpSelectionShell)

// User Supplied Class Members

} ;

extern Widget helpSelectionOkBtn;

/*******************************************************************************
       Declarations of global functions.
*******************************************************************************/

Widget create_helpSelectionShell( swidget UxParent, ServiceID serviceID );

#endif /* _HELPSELECTIONSHELL_INCLUDED */
