
/*******************************************************************************
       outputSelectionShell.h
       This header file is included by outputSelectionShell.cc

*******************************************************************************/

#ifndef _OUTPUTSELECTIONSHELL_INCLUDED
#define _OUTPUTSELECTIONSHELL_INCLUDED

#include <stdio.h>

#ifdef MOTIF
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/MenuShell.h>
#endif /* MOTIF */

#include "UxXt.h"

#ifndef XKLOADDS
#define XKLOADDS
#endif /* XKLOADDS */

/*******************************************************************************
       The definition of the interface class.
       If you create multiple copies of your interface, the class
       ensures that your callbacks use the variables for the
       correct copy.

       For each swidget in the interface, each argument to the Interface
       function, and each variable in the Interface Specific section of the
       Declarations Editor, there is an entry in the class protected section.
       Additionally, methods generated by the builder are declared as 
       virtual. Wrapper functions are generated for callbacks and actions
       to call the user defined callbacks or actions. A UxDestroyContextCB()
       is also generated to ensure a proper clean up of the class after
       the toplevel is destroyed.
*******************************************************************************/

class _UxCoutputSelectionShell: public _UxCInterface
{

// Generated Class Members

public:

 // Constructor Function
 _UxCoutputSelectionShell( swidget UxParent );

 // Destructor Function
 ~_UxCoutputSelectionShell();

 // Interface Function
 Widget _create_outputSelectionShell( void );

protected:

 // Widgets in the interface
 Widget outputSelectionShell;
 Widget bulletinBoard2;
 Widget windowOutputBtn;
 Widget fileOutputBtn;
 Widget outputFileField;
 Widget outputFileSelectBtn;
 Widget separator1;
 Widget outputSelectionOkBtn;
 Widget outputSelectionCancelBtn;
 Widget outputSelectionHelpBtn;

 // Arg List of creation function
 swidget UxParent;

 // Callbacks and their wrappers
 virtual void  popupCB_outputSelectionShell(Widget, XtPointer, XtPointer);
 static void  Wrap_popupCB_outputSelectionShell(Widget, XtPointer, XtPointer);
 virtual void  activateCB_outputFileSelectBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_outputFileSelectBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_outputSelectionOkBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_outputSelectionOkBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_outputSelectionCancelBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_outputSelectionCancelBtn(Widget, XtPointer, XtPointer);

 // Callback function to destroy the context
 static void  UxDestroyContextCB(Widget, XtPointer, XtPointer);

private:
 Widget _build();
 CPLUS_ADAPT_CONTEXT(_UxCoutputSelectionShell)

// User Supplied Class Members

} ;


/*******************************************************************************
       Declarations of global functions.
*******************************************************************************/

Widget create_outputSelectionShell( swidget UxParent );

#endif /* _OUTPUTSELECTIONSHELL_INCLUDED */
