
/*******************************************************************************
       replayShell.h
       This header file is included by replayShell.cc

*******************************************************************************/

#ifndef _REPLAYSHELL_INCLUDED
#define _REPLAYSHELL_INCLUDED

#include <stdio.h>

#ifdef MOTIF
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/MenuShell.h>
#endif /* MOTIF */

#include "UxXt.h"

#ifndef XKLOADDS
#define XKLOADDS
#endif /* XKLOADDS */

/*******************************************************************************
       The definition of the interface class.
       If you create multiple copies of your interface, the class
       ensures that your callbacks use the variables for the
       correct copy.

       For each swidget in the interface, each argument to the Interface
       function, and each variable in the Interface Specific section of the
       Declarations Editor, there is an entry in the class protected section.
       Additionally, methods generated by the builder are declared as 
       virtual. Wrapper functions are generated for callbacks and actions
       to call the user defined callbacks or actions. A UxDestroyContextCB()
       is also generated to ensure a proper clean up of the class after
       the toplevel is destroyed.
*******************************************************************************/

class _UxCreplayShell: public _UxCInterface
{

// Generated Class Members

public:

 // Constructor Function
 _UxCreplayShell( swidget UxParent );

 // Destructor Function
 ~_UxCreplayShell();

 // Interface Function
 Widget _create_replayShell( void );

protected:

 // Widgets in the interface
 Widget replayShell;
 Widget bulletinBoard2;
 Widget replayFileField;
 Widget replaySelectBtn;
 Widget separator1;
 Widget replayOkBtn;
 Widget replayCancelBtn;
 Widget reaplyHelpBtn;
 Widget replayLabel;

 // Arg List of creation function
 swidget UxParent;

 // Callbacks and their wrappers
 virtual void  popupCB_replayShell(Widget, XtPointer, XtPointer);
 static void  Wrap_popupCB_replayShell(Widget, XtPointer, XtPointer);
 virtual void  activateCB_replaySelectBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_replaySelectBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_replayOkBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_replayOkBtn(Widget, XtPointer, XtPointer);
 virtual void  activateCB_replayCancelBtn(Widget, XtPointer, XtPointer);
 static void  Wrap_activateCB_replayCancelBtn(Widget, XtPointer, XtPointer);

 // Callback function to destroy the context
 static void  UxDestroyContextCB(Widget, XtPointer, XtPointer);

private:
 Widget _build();
 CPLUS_ADAPT_CONTEXT(_UxCreplayShell)

// User Supplied Class Members

} ;


/*******************************************************************************
       Declarations of global functions.
*******************************************************************************/

Widget create_replayShell( swidget UxParent );

#endif /* _REPLAYSHELL_INCLUDED */
